version: '3'

services:
  postgres:
    image: 'postgres:10.4-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: ['foreman', 'start', '-f', 'Procfile.docker']
    ports:
      - '3000:5000'
    volumes:
      - 'gems_cache:/gems'
      - '.:/app'

volumes:
  gems_cache:
  redis:
  postgres:
